# see https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
builders:
  copy_builder:
    import: "package:toolchain_gen/builders.dart"
    builder_factories: ["copyBuilder"]
    build_extensions: {".dart": [".copy.g.dart"]}
    auto_apply: dependents
    build_to: source
  state_data:
    import: "package:toolchain_gen/builders.dart"
    builder_factories: ["stateDataBuilder"]
    build_extensions: {".dart": [".data.g.dart"]}
    auto_apply: dependents
    build_to: source
